version: "3.3"

services:
  php:
    image: acrossoffwest/docker-php-fpm:master
    restart: ${RESTART_TYPE:-"no"}
    profiles:
      - fpm
    volumes:
      - "${NGINX_DEFAULT_CONF:-./nginx.d/default.conf}:/etc/nginx/conf.d/default.conf"
      - "${NGINX_CONF:-./nginx.d/nginx.conf}:/etc/nginx/nginx.conf"
      - "${APP_DIR}:/var/www/html"
      - "./supervisor:/etc/supervisor"
      - "./cron.d:/etc/cron.d"
      - "${DEFAULT_PHP_INI:-./php/default.custom.ini}:/usr/local/etc/php/conf.d/custom.ini"
      - "${DEFAULT_PHP_FPM_WWW_CONF:-./php/default.www.conf}:/usr/local/etc/php-fpm/conf.d/custom.ini"
    depends_on:
      - mysql
    networks:
      - database
      - server
    environment:
      - VIRTUAL_HOST=${DOMAINS}
      - LETSENCRYPT_HOST=${DOMAINS}
      - 'COMPOSER_AUTH={"github-oauth": { "github.com": "${COMPOSER_GITHUB_AUTH_TOKEN}" } }'

  mysql:
    image: mariadb:10.6.4
    restart: ${RESTART_TYPE:-"no"}
    profiles:
      - mysql
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_NAME}"
      MYSQL_USER: "${DB_USERNAME}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    networks:
      - database

  redis:
    image: redis:latest
    restart: ${RESTART_TYPE:-"no"}
    profiles:
      - redis
    command: redis-server --requirepass "${REDIS_PASSWORD}"
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_PASSWORD="${REDIS_PASSWORD}"
    volumes:
      - redis-data:/data
    networks:
      - database

networks:
  database:
  server:
  reverseproxy_default:
    external: true

volumes:
  db-data:
  redis-data:
